spring:
  data:
    mongodb:
      uri: "mongodb://admin:test@mongo_27020:27017/cart-service?authSource=admin"
  cloud:
    stream:
      defaultBinder: kafka
      function:
        definition: cartEventFunction
      bindings:
        cartEventFunction-out-0:
          destination: cart-topic
          content-type: application/json
      kafka:
        binder:
          brokers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true 