spring:
  cloud:
    discovery:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: kafka-service:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server-service:8888/eureka/