spring:
  cloud:
    discovery:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/