spring:
  data:
    mongodb:
      uri: "mongodb://admin:test@mongo_27019:27017/product-service?authSource=admin"
  cloud:
    discovery:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/